apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kube-frontend
  template:
    metadata:
      labels:
        app: kube-frontend
    spec:
      containers:
      - name: kube-frontend
        image: mudassirq692/course-frontend:v1
        ports:
        - containerPort: 80
